{
 "title": "lvv-frontend",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "content": "# API" },
  {
   "title": "Create Availability",
   "type": "graph",
   "description": "Create API response code rates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "2XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.createLvvFrontend.ResponseOut.StatusFamily.2XX.Count",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "4XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.createLvvFrontend.ResponseOut.StatusFamily.4XX.Count",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "5XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.createLvvFrontend.ResponseOut.StatusFamily.5XX.Count",
     "project": "lvv-frontend"
    }
   ]
  },
  {
   "title": "Get Availability",
   "type": "graph",
   "description": "Get API response code rates",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "2XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.getLvvFrontend.ResponseOut.StatusFamily.2XX.Count",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "4XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.getLvvFrontend.ResponseOut.StatusFamily.4XX.Count",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "5XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.getLvvFrontend.ResponseOut.StatusFamily.5XX.Count",
     "project": "lvv-frontend"
    }
   ]
  },
  {
   "title": "Update Availability",
   "type": "graph",
   "description": "Update API response code rates",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "2XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.updateLvvFrontend.ResponseOut.StatusFamily.2XX.Count",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "4XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.updateLvvFrontend.ResponseOut.StatusFamily.4XX.Count",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "5XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.updateLvvFrontend.ResponseOut.StatusFamily.5XX.Count",
     "project": "lvv-frontend"
    }
   ]
  },
  {
   "title": "Delete Availability",
   "type": "graph",
   "description": "Delete API response code rates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "2XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.deleteLvvFrontend.ResponseOut.StatusFamily.2XX.Count",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "4XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.deleteLvvFrontend.ResponseOut.StatusFamily.4XX.Count",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "5XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.deleteLvvFrontend.ResponseOut.StatusFamily.5XX.Count",
     "project": "lvv-frontend"
    }
   ]
  },
  {
   "title": "List Availability",
   "type": "graph",
   "description": "List API response code rates",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "2XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.listLvvFrontends.ResponseOut.StatusFamily.2XX.Count",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "4XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.listLvvFrontends.ResponseOut.StatusFamily.4XX.Count",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "5XX",
     "fleet": "lvv-frontend-api",
     "granularity": "300",
     "host": "_all",
     "metric": "LvvFrontendResource.listLvvFrontends.ResponseOut.StatusFamily.5XX.Count",
     "project": "lvv-frontend"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "p99",
     "alias": "Create Latency",
     "fleet": "lvv-frontend-api",
     "granularity": "60",
     "host": "_all",
     "metric": "LvvFrontendResource.createLvvFrontend.Time",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "p99",
     "alias": "Get Latency",
     "fleet": "lvv-frontend-api",
     "granularity": "60",
     "host": "_all",
     "metric": "LvvFrontendResource.getLvvFrontend.Time",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "p99",
     "alias": "Update Latency",
     "fleet": "lvv-frontend-api",
     "granularity": "60",
     "host": "_all",
     "metric": "LvvFrontendResource.updateLvvFrontend.Time",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "p99",
     "alias": "Delete Latency",
     "fleet": "lvv-frontend-api",
     "granularity": "60",
     "host": "_all",
     "metric": "LvvFrontendResource.deleteLvvFrontend.Time",
     "project": "lvv-frontend"
    },
    {
     "ad": "_all",
     "aggregation": "p99",
     "alias": "List Latency",
     "fleet": "lvv-frontend-api",
     "granularity": "60",
     "host": "_all",
     "metric": "LvvFrontendResource.listLvvFrontends.Time",
     "project": "lvv-frontend"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 }, "content": "# Canary" },
  {
   "title": "CreateLvvFrontend Success Rate",
   "type": "graph",
   "description": "Records success of CreateLvvFrontend canary operation",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "mean",
     "alias": "Success",
     "fleet": "lvv-frontend-canary",
     "granularity": "60",
     "host": "_all",
     "metric": "lvv-frontend-canary.createLvvFrontendCall",
     "project": "lvv-frontend"
    }
   ]
  },
  {
   "title": "GetLvvFrontendCompartment Success Rate",
   "type": "graph",
   "description": "Records success of GetLvvFrontendCompartment canary operation",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "mean",
     "alias": "Success",
     "fleet": "lvv-frontend-canary",
     "granularity": "60",
     "host": "_all",
     "metric": "lvv-frontend-canary.getLvvFrontendCall",
     "project": "lvv-frontend"
    }
   ]
  },
  {
   "title": "UpdateLvvFrontend Success Rate",
   "type": "graph",
   "description": "Records success of UpdateLvvFrontend canary operation",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "mean",
     "alias": "Success",
     "fleet": "lvv-frontend-canary",
     "granularity": "60",
     "host": "_all",
     "metric": "lvv-frontend-canary.updateLvvFrontendCall",
     "project": "lvv-frontend"
    }
   ]
  },
  {
   "title": "ListLvvFrontend Success Rate",
   "type": "graph",
   "description": "Records success of ListLvvFrontend canary operation",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "mean",
     "alias": "Success",
     "fleet": "lvv-frontend-canary",
     "granularity": "60",
     "host": "_all",
     "metric": "lvv-frontend-canary.listLvvFrontendCall",
     "project": "lvv-frontend"
    }
   ]
  },
  {
   "title": "DeleteLvvFrontend Success Rate",
   "type": "graph",
   "description": "Records success of DeleteLvvFrontend canary operation",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "mean",
     "alias": "Success",
     "fleet": "lvv-frontend-canary",
     "granularity": "60",
     "host": "_all",
     "metric": "lvv-frontend-canary.deleteLvvFrontendCall",
     "project": "lvv-frontend"
    }
   ]
  }
 ]
}