# To use the OCI Build Service you place a file name ocibuild.conf at the root of your git repo.
# This file, written using the HOCON syntax, will cause a build to automatically be triggered when commits are pushed to your repo.
# The ocibuild.conf file also determines how build service executes the build commands on the source code in your repo.
#
# Build Service Reference: https://confluence.oci.oraclecorp.com/x/7kMZBg
# Where is my build: https://devops.oci.oraclecorp.com/build
# HOCON reference: https://github.com/lightbend/config/blob/master/HOCON.md
# Build Service Slack: #oci_build_svc_users

runnerTag: latest
name: lvv-frontend
team: Network Automation
phoneBookId: network-automation
description: Example-Service
majorversion: 0
minorversion: 1
shortversion: ${majorversion}.${minorversion}
snapshotVersion: ${shortversion}-SNAPSHOT
# BLD_NUMBER contains the build number of this build, which is automatically incremented for each successive build in each branch.
# BLD_BRANCH_SUFFIX is the branch name with a leading hyphen. For instance, if your branch name is foo, then the BLD_BRANCH_SUFFIX would be -foo.
# If your branch is master, the BLD_BRANCH_SUFFIX would be null.
# BuildService will expand ${?BLD_SNAPSHOT_SUFFIX} to -SNAPSHOT, for snapshot branches.
# Note that incase you are not setting the version using the version property,
# ensure that -SNAPSHOT suffix is present to enable publish support to snapshot repository.
version: ${shortversion}${?BLD_BRANCH_SUFFIX}.${BLD_NUMBER}${?BLD_SNAPSHOT_SUFFIX}
# A list of branch names, including special branch name 'pull-requests'.  Determines which branches will trigger on
# commit to bitbucket.
triggerOnCommitBranches: ["master", "pull-requests", "lvv-frontend-*"]
# A list of branch names that should run all defined build steps including those which publish artifacts.
# If a branch is not included in the list, it will be a 'dry-run' build and skips any steps that push dependencies,
# runs scanners, or notifies other services, such as pipelines.
releaseBranches: ["master"]
# For all branches specified using snapshotBranches, BuildService will expand ${?BLD_SNAPSHOT_SUFFIX} to -SNAPSHOT
# which can be used to add the -SNAPSHOT suffix to the version.
snapshotBranches: ["lvv-frontend-*", "pull-requests", "PR-*"]
sendNotificationBranches:  ["master", "pull-requests"]
slackChannels: []
authCompartmentOcid: ocid1.compartment.oc1..aaaaaaaalt3ghoq5nfxenlijgbauts66jr6ntlctdvkp7n34pruewyb3vi4q

steps:
  [
    {
      name: compilesource
      type: node
      nodeVersion: "16.14.0"
      commands: [
        {command: npm, args:"install"}
        {command: npm, args: " exec ojet build --release"}
      ]
      artifacts: 
      [
      "**"
      ]
    }
    # {
    # name: publish_node_artifacts
    # type: publishnode
    # dependsOn: compilesource
    # packageDir: na
    # repository: build-service-test-npm-local
    # },
  ]
