# To use the OCI Build Service you place a file name ocibuild.conf at the root of your git repo.
# This file, written using the HOCON syntax, will cause a build to automatically be triggered when commits are pushed to your repo.
# The ocibuild.conf file also determines how build service executes the build commands on the source code in your repo.
#
# Build Service Reference: https://confluence.oci.oraclecorp.com/x/7kMZBg
# Where is my build: https://devops.oci.oraclecorp.com/build
# HOCON reference: https://github.com/lightbend/config/blob/master/HOCON.md
# Build Service Slack: #oci_build_svc_users

runnerTag: latest
name: lvv-frontend
team: Network Automation
phoneBookId: network-automation
description: Example-Service
majorversion: 0
minorversion: 1
shortversion: ${majorversion}.${minorversion}
version: ${shortversion}.${BLD_NUMBER}
triggerOnCommitBranches: ["master", "pull-requests", "beta"]
# Remove "pull-requests" after LA.
releaseBranches: ["master", "develop"]
sendNotificationBranches:  ["master", "pull-requests"]
slackChannels: []
authCompartmentOcid: ocid1.compartment.oc1..aaaaaaaalt3ghoq5nfxenlijgbauts66jr6ntlctdvkp7n34pruewyb3vi4q

steps:
  [
    {
      name: compilesource
      type: node
      nodeVersion: "18.19.0"
      runnerImage: build-runner-node-ol8
      commands: [
        {command: npm, args:"install"}
        {command: npm, args: "list"}
        {command: npm, args: "version "${version}}
        {command: npm, args: "exec ojaf"}
        {command: npm, args: "exec -- ojet build web --release"}
      ]
      artifacts: [
      "**"
      ]
    },
    {
      name: publish_node_artifacts
      type: publishnode
      dependsOn: compilesource
      repository: build-service-test-npm-local
      artifacts: [
        "**"
      ]
    },
    {
      name: dockerize_ui
      type: dockerizer
      dependsOn: compilesource
      dockerBuildPwd: "."
      dockerFile: "Dockerfile"
      platform: "linux/arm64"
      artifacts: [
        "**"
      ]
    },
    {
      name: publish_docker
      type: publishdocker
      dependsOn: dockerize_ui
      repository: odo-docker-signed-local
      # imageName: ${name} # after LA
      imageName: ${name}
      platform: "linux/arm64"
    }
  ]
