/**
  Copyright (c) 2015, 2025, Oracle and/or its affiliates.
  Licensed under The Universal Permissive License (UPL), Version 1.0
  as shown at https://oss.oracle.com/licenses/upl/

*/
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const InlineChunkHtmlPlugin = require('inline-chunk-html-plugin')
const HTMLInlineCSSWebpackPlugin = require("html-inline-css-webpack-plugin").default;
const TerserPlugin = require('terser-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  /**
   *
   * @param {object} options.context - ojet build context which contains useful fields like
   * buildType
   * @param {object} options.config - Default webpack config generated by ojet. You can
   * add to it, remove from it or update it using webpack-merge which was
   * installed alongside webpack. If desired, you can create your own config
   * and return it which will override the default config. Consider the examples below:
   *
   * 1. Adding a new plugin or optimization configuration into the default config:
   *
   *    config.plugins.push(new SomeWebpackPlugin());
   *
   *    config.optimization = {...config.optimization, splitChunks: { chunks: 'async' }};
   *
   *    config.output.publicPath = 'https://yourcdnlink.com/';
   *
   * 2. Alternatively, you can implement a custom config to override the default:
   *
   *    config = {};
   *
   *    config.plugins = [new SomeWebpackPlugin()];
   *
   *    config.optimization = {minimize: true, splitChunks: { chunks: 'all' }};
   *
   *    config.module.rules.push({test: /\.css$/, use: ['style-loader', 'css-loader']});
   *
   *    config.devServer = {static: {directory: path.join(_dirname, 'web')}, hot: true, port: 9000};
   *
   * @returns {object|undefined}
   */
  webpack: ({ context, config }) => {
    const requestedDevServerPort = Number.parseInt(
      process.env.OJET_DEV_SERVER_PORT || process.env.PORT || "",
      10
    );
    config.output.path = path.resolve(__dirname, './web');
    config.output.publicPath = '';
    config.output.clean = false;
    config.plugins.push(
      new CopyWebpackPlugin({
        patterns: [
          {
            from: path.resolve(__dirname, 'src/landing/resources'),
            to: path.resolve(__dirname, 'web/landing/resources')
          }
        ]
      })
    );
    config.resolve.alias = {
      ...config.resolve.alias,
      '@oracle/oraclejet-preact': path.resolve(__dirname, 'node_modules/@oracle/oraclejet-preact/amd'),
      '@oracle/oraclejet-core-pack': path.resolve(__dirname, 'node_modules/@oracle/oraclejet-core-pack/oj-c'),
      'oj-c': path.resolve(__dirname, 'node_modules/@oracle/oraclejet-core-pack/oj-c'),
    };
    if (context.buildType === 'release') {
      config.optimization = { minimize: true, splitChunks: { chunks: 'all' } };
      config.optimization.minimizer = [
        new TerserPlugin({
          parallel: true,
        }),
      ];
      const htmlPlugin = config.plugins.find(
        p => p instanceof HtmlWebpackPlugin
      );

      if (htmlPlugin) {
        htmlPlugin.options.inlineSource = '.(js|css)$';
      }
      // config.plugins.push(new InlineChunkHtmlPlugin(HtmlWebpackPlugin, [/.js/]));
      // config.plugins.push(new HTMLInlineCSSWebpackPlugin())
    } else {
      // update config with development options
      if (Number.isFinite(requestedDevServerPort) && requestedDevServerPort > 0) {
        config.devServer = {
          ...(config.devServer || {}),
          port: requestedDevServerPort,
          client: {
            overlay: {
              runtimeErrors: (error) => {
                if (error?.message === "ResizeObserver loop completed with undelivered notifications.") {
                  console.error(error)
                  return false;
                }
                return true;
              },
            },
          },

        };
      }
    }
    // only have to return if new config object was created but
    // since it doesn't matter always returning the config is good
    // practice
    return { context, webpack: config };
  }
};

