const workOrders = {
    "items": [
        {
            "id": "000001",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000001",
            "timeCreated": "2024-08-21T10:00:00Z",
            "timeUpdated": "2024-08-28T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0101",
            "createdBy": "namename",
            "vendorName": "namename",
            "lifecycleState": "SUCCEEDED"
        },
        {
            "id": "000002",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000002",
            "timeCreated": "2024-08-22T10:00:00Z",
            "timeUpdated": "2024-08-28T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0102",
            "createdBy": "namename",
            "vendorName": "namename",
            "lifecycleState": "IN_PROGRESS"
        },
        {
            "id": "000003",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000003",
            "timeCreated": "2024-08-23T10:00:00Z",
            "timeUpdated": "2024-08-27T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0103",
            "createdBy": "namename",
            "vendorName": "namename",
            "lifecycleState": "IN_PROGRESS"
        },
        {
            "id": "000004",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000004",
            "timeCreated": "2024-08-24T10:00:00Z",
            "timeUpdated": "2024-08-27T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0104",
            "createdBy": "namename",
            "vendorName": "namename",
            "lifecycleState": "IN_PROGRESS"
        },
        {
            "id": "000005",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000005",
            "timeCreated": "2024-08-25T10:00:00Z",
            "timeUpdated": "2024-08-26T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0105",
            "createdBy": "namename",
            "vendorName": "namename",
            "lifecycleState": "IN_PROGRESS"
        },
        {
            "id": "000006",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000006",
            "timeCreated": "2024-08-26T10:00:00Z",
            "timeUpdated": "2024-08-26T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0201",
            "createdBy": "namename",
            "vendorName": "namename",
            "lifecycleState": "IN_PROGRESS"
        },
        {
            "id": "000007",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000007",
            "timeCreated": "2024-08-27T10:00:00Z",
            "timeUpdated": "2024-08-25T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0202",
            "createdBy": "namename",
            "vendorName": null,
            "lifecycleState": "IN_PROGRESS"
        },
        {
            "id": "000008",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000008",
            "timeCreated": "2024-08-28T10:00:00Z",
            "timeUpdated": "2024-08-25T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0203",
            "createdBy": "namename",
            "vendorName": "namename",
            "lifecycleState": "SUCCEEDED"
        },
        {
            "id": "000009",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000009",
            "timeCreated": "2024-08-29T10:00:00Z",
            "timeUpdated": "2024-08-24T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0204",
            "createdBy": "namename",
            "vendorName": "namename",
            "lifecycleState": "SUCCEEDED"
        },
        {
            "id": "000010",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000010",
            "timeCreated": "2024-08-30T10:00:00Z",
            "timeUpdated": "2024-08-23T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0205",
            "createdBy": "namename",
            "vendorName": "namename",
            "lifecycleState": "SUCCEEDED"
        },
        {
            "id": "000011",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000011",
            "timeCreated": "2024-08-31T10:00:00Z",
            "timeUpdated": "2024-08-22T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0206",
            "createdBy": "Not Assigned",
            "vendorName": null,
            "lifecycleState": "SUCCEEDED"
        },
        {
            "id": "000012",
            "workOrderDefinitionId": "def-001",
            "displayName": "QC Work Order 000012",
            "timeCreated": "2024-09-01T10:00:00Z",
            "timeUpdated": "2024-08-21T00:00:00Z",
            "regionId": "us-chicago-1",
            "buildingId": "bldg-1",
            "dataHallId": "dh-1",
            "roomId": "abc1.2",
            "rackLocationId": "0207",
            "createdBy": "Not Assigned",
            "vendorName": null,
            "lifecycleState": "SUCCEEDED"
        }
    ]
}

export default workOrders;
